1085 restructure foundry contract directory
Bisonai/orakl pull request #1089
Opened 2024-01-30 08:05 UTC by KelvinThai

# Description

This PR restructure the contract folder, fix github actions

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Deployment

- [ ] Should publish npm package
- [ ] Should publish Docker image

2024-01-30 14:15 UTC, nick-bisonai requested changes
- I assume the initial request was to put projects inside `contracts` folder rather than having scattered path as `contracts-v0.1` and `contracts-v0.2`.

so structure would be as followed if I understood correctly
```
contracts
├─ v0.1 (hardhat project)
├─ v0.2 (foundry project)
```
- I think it'd unnecessary to keep `v0.1` path inside `scripts`, `src`, and `test` folder since the versioning is done in parent path
- It'd be better to keep all github workflow files inside `.gitgub/workflows` folder rather than having it separated in project folder

2024-01-31 01:32 UTC, martinkersner commented
> I think we alr agreed up on this structure in the sync meeting. Anyway, it does not make much impact ![image](https://private-user-images.githubusercontent.com/54656638/301007510-ac0c984e-ba2c-408a-a09d-9b1f7a8964ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NjQ3NjAsIm5iZiI6MTcwNjY2NDQ2MCwicGF0aCI6Ii81NDY1NjYzOC8zMDEwMDc1MTAtYWMwYzk4NGUtYmEyYy00MDhhLWEwOWQtOWIxZjdhODk2NGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDAxMjc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwNDRiZWRhMDZhZjZjMmY1YTM2NzA5OGU5ZDk4ZjljNjE0ZWY2Y2U3OWZlZmJiMWU5YWY0YTRkYzk0ODY2NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1_e8A2IVTLOHegcUaUoYPG-DZCpObPK1K05RDgMcc6o)

Nick's approach is also fine, but let's keep it as it is in this PR. Later, we can do update it again :)

2024-01-31 02:35 UTC, martinkersner approved these changes
LGTM!

2024-01-31 02:35 UTC, martinkersner commented on vrf/README.md
> +###
@KelvinThai Can you please remove this?

```suggestion

```

2024-01-31 02:47 UTC, nick-bisonai commented on contracts-v0.2/.github/workflows/test.yml
is there a specific reason for this file to stay in this project path?
if not, please move the github action file inside `contracts-v0.2` folder

2024-01-31 02:57 UTC, KelvinThai commented on contracts-v0.2/.github/workflows/test.yml
Agreed, let's keep all workflow files in the root project directory

2024-01-31 03:35 UTC, nick-bisonai approved these changes

2024-01-31 07:17 UTC, merged